INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (1,'Health',0,6,57,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (2,'Beauty',0,4,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (3,'Makeup',2,3,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (4,'Mystery Bundle Blowout!',0,1,62,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (5,'Fashion',0,4,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (8,'Skincare',2,1,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (9,'Hair',2,2,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (10,'Home',0,6,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (12,'Music',10,0,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (14,'Gifts',0,2,36,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (15,'Gifts for Him',0,0,36,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (16,'Gifts for Her',0,0,36,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (17,'Stocking Stuffers',0,0,36,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (18,'Handbags',5,4,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (20,'Clothing',5,0,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (21,'Sunglasses',5,4,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (22,'Tools',2,4,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (24,'Hats',5,5,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (25,'Staff Picks',0,0,3,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (27,'Past Box Faves',0,0,1,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (29,'Lifestyle',0,6,32,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (30,'Last Call',0,9,57,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (31,'Accessories',5,1,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (40,'Shop By Trend',0,2,0,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (57,'Experiences',0,4,0,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (75,'Bath & Body',2,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (76,'Nails',2,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (77,'Tools & Brushes',2,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (78,'Apparel',5,2,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (79,'Jewelry',5,6,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (80,'Wellness',0,8,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (81,'Fitness ',80,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (82,'Health Care ',80,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (83,'Personal Care ',80,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (84,'Bed & Bath',10,1,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (85,'Bedding',10,0,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (86,'Rugs',10,3,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (87,'Kitchen & Dining',10,7,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (88,'Lighting ',10,9,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (89,'Outdoor',10,1,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (90,'Décor',10,4,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (91,'Storage & Organization ',10,11,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (92,'Tech',0,7,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (93,'Cameras',92,0,88,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (94,'Cell Phone Accessories ',92,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (95,'Audio ',92,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (97,'Room Fragrance',10,10,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (98,'Luggage & Travel',10,8,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (100,'Office',10,5,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (101,'Oral Care',80,0,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (103,'Desk To Dinner',40,2,0,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (104,'Resort Ready',40,3,0,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (105,'Perfect Party Host',40,4,0,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (106,'Start Clean',40,5,0,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (107,'Bundles',0,1,0,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (108,'Entertainment',10,2,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (109,'Eyewear',5,3,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (110,'Wearable Technology',92,4,68,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (111,'Food & Drink',10,8,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (112,'Aromatherapy',80,2,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (113,'Household Cleaning',10,6,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (114,'Pets',10,10,75,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (121,'Tech Accessories',92,3,68,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (123,'Donate',0,3,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (126,'reVive Light Therapy®',4,1,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (127,'Caravan',4,2,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (128,'Summer & Rose',4,3,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (129,'Elemis',4,4,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (131,'Shoshanna',4,6,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (133,'111SKIN',4,8,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (134,'AG Hair',4,9,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (135,'Ciaté',4,10,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (136,'Book Club',40,7,0,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (137,'Boxes',0,10,64,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (138,'Cooking Tools',0,4,67,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (139,'Cookware',138,1,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (140,'Bakeware',138,2,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (141,'Cutlery & Cooking Utensils',138,3,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (142,'Kitchen',0,5,67,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (143,'Storage  & Organization',142,1,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (144,'Gadgets & Appliances',142,2,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (145,'Kitchen Accessories',142,3,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (146,'Dining',0,6,67,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (147,'Drinkware',146,1,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (148,'Dinnerware',146,2,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (149,'Entertaining ',0,8,67,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (150,'Barware',149,1,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (151,'Serveware',149,2,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (152,'Picnic Party',149,3,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (157,'Shop By Brand',0,2,67,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (159,'Art + Cook',157,1,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (160,'Denmark Tools',157,4,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (161,'Tuxton Home',157,7,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (162,'kate spade new york',157,4,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (164,'Chic and Tonic',4,9,64,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (165,'Tabletop',146,3,67,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (167,'Furniture',10,3,88,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (174,'New Arrivals',0,1,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (177,'Gifts For Mom',0,3,75,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (186,'Summer Box Brands',0,0,76,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (187,'Autumnal Accessories',40,0,82,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (188,'Working In & Working Out',40,0,82,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (189,'Sweater Weather',40,0,82,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (190,'Inside Out Beauty',40,0,82,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (191,'Elevated Essentials',40,0,82,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (192,'Coola',186,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (193,'Isaac Mizrahi',186,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (194,'Yumi Kim',186,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (198,'Terre Mere',186,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (199,'TOMS',186,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (200,'Brands We Love',0,2,76,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (201,'Box Brands',0,0,64,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (202,'Spongellé',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (203,'Perricone MD',200,5,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (204,'Daily Concepts',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (206,'Ahava',200,1,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (207,'Algenist',200,2,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (209,'FoxyBae',200,4,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (211,'Wellthy',200,9,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (212,'Tula',200,8,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (213,'Under $20',107,1,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (214,'Under $30',107,2,80,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (215,'Under $40',107,3,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (216,'tarte™',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (217,'Bundles Over $40',107,4,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (218,'Buy More, Save More',107,5,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (219,'Curated by Katie',107,0,81,0);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (220,'Zoe Ayla',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (221,'Grown Alchemist',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (222,'The Beauty Crop',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (223,'Murad®',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (224,'dr. brandt skincare',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (225,'R+Co',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (226,'Kate Somerville',200,0,76,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (227,'',174,0,87,1);
INSERT INTO shop_addons_categories (id,name,parent_id,`ordering`,campaign_id,published) VALUES (228,'Innovative Tech',92,0,0,1);
